SUPABASE_HOST="aws-1-ap-southeast-2.pooler.supabase.com"
SUPABASE_PASSWORD="KdXqFCqD0JtVkr3B"
SUPABASE_URL="https://yrwwtrgshppxdspizvdg.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyd3d0cmdzaHBweGRzcGl6dmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MDk2NjQsImV4cCI6MjA3NzI4NTY2NH0.bmq_fUcqDs5QkOJgZlfuXCxJu5v8TJhAaOGjsAg5u10"